### ISSUE TITLE
Support Setup Guide in GUI

### ISSUE THREAD

**Issue by JacobLinCool** [UniCourse-TW/realm#17]
Maybe we can show a setup screen when system detects there is only one "admin" user.

The setup guide will ask for the username of the first user and automate the process of user registration with selected roles.

**Comment by uier** [comment]
A relatively simple way is to redirect developer to register UI (`/auth` page) with pre-filled username & invitation code after clicking Get Started.

And also the role need to be kept for registering user with corresponding role.

1. Developer enters the Username and the Role, then clicks Get Started.
2. We obtain an Invitation Code via server query, then redirect developer to `/auth?username=<username>&role=<role>&code=<invitationCode>` for registeration.
3. Developer submits registeration form, then we create the user and set the role.

- [x] home page UI
- [ ] home page TS logic
- [ ] auth page TS logic
- [ ] GET invitation code API
- [ ] PATCH user role API

**Comment by JacobLinCool** [comment]
Maybe we don't need to implement the GET invitation code API? Just simply create the first invitation code at the setup (use `MERGE`) and use the code?

BTW the role selector should allow multiple selections.

**Comment by uier** [comment]
> Maybe we don't need to implement the GET invitation code API? Just simply create the first invitation code at the setup (use `MERGE`) and use the code?

Sure, if could, I'll store the value of the first invitation code in .env instead of hard coding.

> BTW the role selector should allow multiple selections.

Okay, thanks for the reminder.
